services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=theotherdatasource'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'